FROM node:16-alpine

WORKDIR /usr/src/app

COPY . .

RUN npm install
RUN npm run build
RUN npm install -g serve
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

USER appuser

EXPOSE 5678

CMD ["serve", "-s", "-l", "5678", "build"]